import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import Footer from "../components/Footer";
import SidebarContainer from "@/components/sidebar/SidebarContainer";
import BackgroundContainer from "@/components/backgroundContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  	title: "Tabaq Diet Tracker",
  	description: "Generated by bees",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      	<body className={`${inter.className} relative min-h-screen`}>
        <BackgroundContainer/>
        <div className="flex flex-col min-h-screen relative z-10">
			<SidebarContainer/>
			<div className="flex-grow">{children}</div>
			<Footer/>
        </div>
    	</body>
    </html>
	);
}